grpc_build:
	go build -ldflags "-X main.DATABASEURL=academy08:78fqoLQpJ9XXpAab8fVuQmbzdmhACZ@(ca-academy-db.c9ml7do7yvmn.ap-northeast-1.rds.amazonaws.com:3306)/academy08?parseTime=true" -o ./bin/ ./grpc
	go build -o ./bin/ ./grpc_client